#!/usr/bin/env bash
# Script to backup all datatabases and compress it.

d=$(date +"%d")
m=$(date +"%m")
y=$(date +"%Y")
file_name="$d-$m-$y.tar.gz"
mysqldump --all-databases -u root -p="$1" >backub.sql
tar -czvf "$file_name" backup.sql
