#!/usr/bin/env bash

#  all processes  PS 
ps axfo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm | while read -r user pid cpu mem vsz rss tty stat start time cmd
do
  # Print info
  echo "$user $pid $cpu $mem $vsz $rss $tty $stat $start $time $cmd" 
  
  # Indent child processes
  while read -r user pid cpu mem vsz rss tty stat start time cmd
  do
    echo "  $_ $cpu $mem $vsz $rss $tty $stat $start $time $cmd"
  done < <(ps axfo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm --ppid $pid)

done
