#!/usr/bin/env bash


# Loop indefinitely printing messages with a 2 Sec delay
# print "To infinity and beyond"  
# Sleep for 2 seconds

while true
do

  echo "To infinity and beyond"  

  
  sleep 2

  trap 'echo "I am invincible!!!"' SIGTERM

done
