#!/usr/bin/env bash

for i in {1..100}; do
    output=""
    
    [ $((i % 3)) = 0 ] && output+="Fizz"
    [ $((i % 5)) = 0 ] && output+="Buzz"
    
    [ -z "$output" ] && output="$i"
    
    echo "$output"
done
