#!/usr/bin/env bash
# Loop 10 times, displaying "Best School" 9 times. On the 9th
# iteration display "Hi", instead.

for (( i = 1; i <= 10; i++ )); do
  if [ "$i" == 9 ]; then
    echo "Hi"
  else
    echo "Best School"
  fi
done
