#!/usr/bin/env bash

# Display hours and minutes for 12 hours and 59 minutes

hour=0
while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  minute=0
  while [ $minute -le 59 ]; do
    echo "Minute: $minute"
    ((minute++))
  done
  ((hour++))
done
