#!/usr/bin/env bash
# Display contents of the current directory in list format with the part
# of the name after the first dash removed.

for f in *; do
    if [[ $f == *-* ]]; then
        echo "$f" | cut -d'-' -f2-
    else
        echo "$f"
    fi
done
