#!/usr/bin/env bash
#Get information about file "school"
filename="school"

if [ -e "$filename" ]; then
    echo "$filename file exists"
    [ -s "$filename" ] && echo "$filename file is not empty"
    [ -f "$filename" ] && echo "$filename is a regular file"
else
    echo "$filename file does not exist"
fi
